In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
from transphone.data.loader import read_loader
from transphone.data.dataset import read_dataset
import torch.optim as optim
from transphone.model.lstm import G2P
import torch.nn as nn
from torch.utils.data import random_split
import torch
from transphone.data.utils import pad_sos_eos
from torch.utils.tensorboard import SummaryWriter

In [6]:
dataset = read_dataset('eng')
training_cnt = int(len(dataset)*0.95)
test_cnt = len(dataset) - training_cnt

train_dataset, test_dataset = random_split(dataset, [training_cnt, test_cnt], generator=torch.Generator().manual_seed(42))

In [43]:
torch.randn(10,3)

tensor([[ 0.1114, -1.0056, -0.5639],
        [ 0.1417,  0.9793,  0.5589],
        [-1.1789, -0.3318, -0.1962],
        [ 0.2602,  0.7118, -1.3629],
        [ 0.5322, -0.7265, -1.1208],
        [-0.4077,  2.6134,  1.4054],
        [ 1.8550,  1.6469, -0.6377],
        [ 1.5292, -0.8430,  0.0261],
        [ 0.5763,  0.8013,  0.3980],
        [-2.3939,  0.0119, -0.2357]])

In [7]:
import editdistance

In [9]:
editdistance.eval([1,3,2], [1,2,4,4])

3

In [44]:
w = torch.empty((2,3))

In [46]:
nn.init.normal_(w)

tensor([[ 0.6583, -1.0203,  0.9597],
        [ 0.9323, -1.1376,  0.0805]])

In [47]:
w

tensor([[ 0.6583, -1.0203,  0.9597],
        [ 0.9323, -1.1376,  0.0805]])

In [37]:
torch.zeros(10, dtype=torch.long)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [42]:
torch.randint(1, 5, (10,))

tensor([4, 1, 1, 2, 3, 3, 3, 2, 3, 1])

In [35]:
torch.DoubleTensor([1,2,3])

tensor([1., 2., 3.], dtype=torch.float64)

In [34]:
torch.LongTensor([1,2,3])

tensor([1, 2, 3])

In [18]:
class Model(nn.Module):
    
    def __init__(self):
        super().__init__()
        self.embed = nn.Embedding(10, 4)
        a = nn.Linear(10, 8)
        b = torch.rand(10)
        self.b = a(b)

In [19]:
m = Model()

In [20]:
list(m.parameters())

[Parameter containing:
 tensor([[ 0.9718, -0.6111, -0.1088,  1.0160],
         [-0.5512, -0.6477, -0.2726, -0.7290],
         [-1.0155, -0.1948, -0.4455,  0.4068],
         [-0.9128,  0.8814,  1.4740, -1.2771],
         [-1.2165, -1.1735, -0.5921,  0.0789],
         [-0.3989,  1.3849,  1.6966,  0.2661],
         [-0.4152, -0.2792, -0.3884,  1.1886],
         [ 1.2245, -2.2078, -0.2530,  2.5116],
         [-0.4769,  0.0075,  0.4783,  0.2715],
         [-1.5386, -0.0486, -0.1070, -0.4601]], requires_grad=True)]

In [21]:
m._modules

OrderedDict([('embed', Embedding(10, 4))])

In [22]:
list(m.modules())

[Model(
   (embed): Embedding(10, 4)
 ),
 Embedding(10, 4)]

In [63]:
lstm = nn.LSTM(4, 8, 1, batch_first=True)

In [59]:
input = torch.randn((2,3,4))

In [60]:
input.size()

torch.Size([2, 3, 4])

In [77]:
logsoft = nn.LogSoftmax(dim=1)

In [81]:
t = torch.tensor([[-0.1, -0.2], [-0.3, -0.2]])

In [82]:
logsoft(t)

tensor([[-0.6444, -0.7444],
        [-0.7444, -0.6444]])

In [93]:
from torch.utils.data import random_split
from torch.utils.data import DataLoader

In [89]:
a, b = random_split(range(100), [60, 40], generator=torch.Generator().manual_seed(42))

In [90]:
len(a)

60

In [91]:
len(b)

40

In [94]:
loader = DataLoader(a, batch_size=4)

In [98]:
it = iter(loader)

In [100]:
for batch in it:
    print(batch)

tensor([42, 96, 62, 98])
tensor([46, 95, 60, 24])
tensor([78, 16, 68, 70])
tensor([11, 13, 97, 52])
tensor([99, 19, 71, 10])
tensor([89, 86, 18, 40])
tensor([ 5, 38,  9, 82])
tensor([83, 43, 32, 94])
tensor([67, 93, 75, 59])
tensor([79,  1, 50, 73])
tensor([66, 45, 63, 58])
tensor([22,  3, 87,  4])
tensor([61, 51, 12, 74])
tensor([21, 20,  6, 35])
tensor([44, 48, 37, 33])
