In [88]:
import torch
import torch.nn as nn

In [147]:
def generate_square_subsequent_mask(sz):
    mask = (torch.triu(torch.ones((sz, sz))) == 1).transpose(0, 1)
    mask = mask.float().masked_fill(mask == 0, float('-inf')).masked_fill(mask == 1, float(0.0))
    return mask

In [152]:
(torch.triu(torch.ones(4,4))==1).transpose(0,1)

tensor([[ True, False, False, False],
        [ True,  True, False, False],
        [ True,  True,  True, False],
        [ True,  True,  True,  True]])

In [153]:
generate_square_subsequent_mask(4)

tensor([[0., -inf, -inf, -inf],
        [0., 0., -inf, -inf],
        [0., 0., 0., -inf],
        [0., 0., 0., 0.]])

In [163]:
def create_mask(src, tgt):
    src_seq_len = src.shape[1]
    tgt_seq_len = tgt.shape[1]

    tgt_mask = generate_square_subsequent_mask(tgt_seq_len)
    src_mask = torch.zeros((src_seq_len, src_seq_len)).type(torch.bool)

    src_padding_mask = (src == 0).transpose(0, 1)
    tgt_padding_mask = (tgt == 0).transpose(0, 1)
    return src_mask, tgt_mask, src_padding_mask, tgt_padding_mask

In [161]:
src = torch.LongTensor([[2,3,1,4], [1,2,0,0]])
tgt = torch.LongTensor([[1,2,3,4], [1,2,3,0]])

In [164]:
create_mask(src, tgt)

(tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[0., -inf, -inf, -inf],
         [0., 0., -inf, -inf],
         [0., 0., 0., -inf],
         [0., 0., 0., 0.]]),
 tensor([[False, False],
         [False, False],
         [False,  True],
         [False,  True]]),
 tensor([[False, False],
         [False, False],
         [False, False],
         [False,  True]]))

In [165]:
src==0

tensor([[False, False, False, False],
        [False, False,  True,  True]])

In [168]:
a.new_ones(

<function Tensor.new_ones>

In [154]:
length=3
torch.tril(torch.ones((length, length))).bool()

tensor([[ True, False, False],
        [ True,  True, False],
        [ True,  True,  True]])

In [38]:
length = torch.LongTensor([3,5,4])

In [75]:
lstm = nn.LSTM(2,4,3, batch_first=True)

In [76]:
a = torch.randn(3,5,2)

In [86]:
c = lstm(a)[0]

In [90]:
a.shape

torch.Size([3, 5, 2])

In [110]:
b = torch.randn(2,3,6)

In [107]:
b

tensor([[-1.1678, -1.1470, -0.0738, -0.9761, -1.3659,  1.0630],
        [ 1.0190, -0.2465,  0.9873,  1.6251,  0.2916, -0.9709]])

In [93]:
torch.matmul(a,b).shape

torch.Size([3, 5, 6])

In [113]:
b

tensor([[[ 0.3617, -2.2156,  0.7410,  0.0731,  0.0196,  0.1385],
         [-0.3073,  0.3731,  0.4132,  0.7034,  0.7127, -0.4950],
         [-1.0415, -1.0219,  0.2790, -0.3420, -0.8698, -0.6924]],

        [[ 1.4119, -1.4886, -1.0737,  0.5419, -0.6535, -0.3455],
         [ 2.1027,  0.8228,  0.5696, -0.4723,  1.3933, -0.6038],
         [ 0.4663,  0.0967, -0.6034,  1.0090, -0.0249,  0.2981]]])

In [120]:
torch.div(b,b).shape

torch.Size([2, 3, 6])

In [122]:
b.shape

torch.Size([2, 3, 6])

In [123]:
c = torch.randn(6,4)

In [127]:
torch.matmul(b,c).shape

torch.Size([2, 3, 4])

In [128]:
a = torch.randn(2,3,4,5)

In [140]:
b = torch.randn(1,3,5,4)

In [141]:
torch.matmul(a,b).shape

torch.Size([2, 3, 4, 4])

In [144]:
torch.nn.Transformer

torch.nn.modules.transformer.Transformer

In [133]:
torch.bmm(a,b)

RuntimeError: Expected 3-dimensional tensor, but got 4-dimensional tensor for argument #1 'batch1' (while checking arguments for bmm)

In [99]:
b = torch.randn(4, 1)

In [100]:
c = torch.randn(1,4)

In [103]:
torch.mm(b,c)

tensor([[-0.0137,  0.0517,  0.0653, -0.0174],
        [-0.0298,  0.1127,  0.1424, -0.0379],
        [-0.1176,  0.4452,  0.5623, -0.1495],
        [-0.3925,  1.4865,  1.8772, -0.4993]])

In [87]:
c.shape

torch.Size([3, 5, 4])

In [39]:
mask = torch.arange(torch.max(length)).unsqueeze(0) < length.unsqueeze(1)

In [63]:
a = [2,3,1]

In [65]:
a = a[:-1] if a[-1] == 1

SyntaxError: invalid syntax (<ipython-input-65-92e9b022e783>, line 1)

In [68]:
if a[-1] == 1:
    a = a[:-1]

In [69]:
a

[2, 3]

In [64]:
a

[2, 3, 1]

In [40]:
torch.max(length)

tensor(5)

In [41]:
length.unsqueeze(-1)

tensor([[3],
        [5],
        [4]])

In [42]:
torch.sum(mask, dim=1)

tensor([3, 5, 4])

In [57]:
b = torch.randn(3,5)

In [54]:
b

tensor([[ 1.0551,  0.2301, -0.7556,  0.6130, -1.2613],
        [ 0.0261,  0.4010, -1.4695, -0.0040, -0.9201],
        [ 0.2779,  0.9137,  1.1690, -1.3279,  0.5561]])

In [58]:
mask

tensor([[ True,  True,  True, False, False],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True, False]])

In [61]:
b.masked_fill_(~mask, -np.inf)

tensor([[ 1.3503, -0.2101,  0.5982,    -inf,    -inf],
        [ 0.6641, -0.8612,  0.2389, -1.1343,  1.1640],
        [ 1.1004, -1.2243, -1.1901, -0.5063,    -inf]])

In [62]:
b

tensor([[ 1.3503, -0.2101,  0.5982,    -inf,    -inf],
        [ 0.6641, -0.8612,  0.2389, -1.1343,  1.1640],
        [ 1.1004, -1.2243, -1.1901, -0.5063,    -inf]])

In [46]:
b*mask.unsqueeze(-1)

tensor([[[ 0.8727, -0.7781],
         [ 0.9685, -0.0288],
         [-0.5258, -0.4468],
         [-0.0000,  0.0000],
         [-0.0000, -0.0000]],

        [[ 0.9425, -2.1465],
         [ 0.9071, -1.7719],
         [-1.2322,  0.0191],
         [-0.8855,  0.3241],
         [-0.4546,  1.1948]],

        [[-0.5236, -0.8632],
         [ 0.9206, -0.2386],
         [ 0.6267,  0.7634],
         [ 0.8266,  0.0284],
         [-0.0000, -0.0000]]])

In [24]:
from torch.nn.utils.rnn import pad_sequence

In [25]:
a = torch.LongTensor([1,2,3,0,0])
b = torch.LongTensor([4,5])

In [27]:
c = pad_sequence([a,b], batch_first=True)

In [34]:
mask = (c != 0)

In [36]:
torch.sum(mask, dim=1)

tensor([3, 2])